### ISSUE TITLE
What should passing null do?

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/boa#2]
On a similar note to the issue Tyler raised today — what about a null input?

- return null
- return empty string
- raise exception e.g., `TypeError`
- other?

@schnie @tylermichael What do you guys think?

**Comment by schnie** [comment]
Looks like the python `stringcase.snakecase` returns `none` and node `lodash.snakecase` returns an empty string. I can see both ways, but I kind of like the predictability of returning an empty string.
